#!/bin/bash

set -euo pipefail
. /.functions

set_or_default BASE_DIR "/app"
set_or_default HOME_DIR "${BASE_DIR}/solr"
set_or_default MODULES_DIR "${HOME_DIR}/modules"

eyes "Remove the HDFS plugin for now"
# We need to remove the HDFS plugin for now ... or update
# the hadoop-client-runtime to a version newer than 3.4.2
# (the current version is 3.4.0, but it still uses bad
# versions of commons-lang3 and commons-compress)
rm -rf "${MODULES_DIR}/hdfs"
ok "Remediation complete"
